# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0003_auto_20171025_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
