# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0004_notification_notif_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profics',
            field=models.IntegerField(default=0),
        ),
    ]
