# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0005_profile_profics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pict',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profics',
            field=models.IntegerField(default=1),
        ),
    ]
