# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0006_auto_20171028_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='uni',
            field=models.CharField(default='University of Sydney', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='AU', max_length=30),
        ),
    ]
