# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0007_auto_20171030_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pict',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='uni',
            field=models.CharField(default='University of Sydney', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profics',
            field=models.IntegerField(default=1),
        ),
    ]
