# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0007_auto_20171029_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pict',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
