# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0008_auto_20171029_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pict',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
