# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0008_auto_20171030_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='AU', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profics',
            field=models.IntegerField(default=0),
        ),
    ]
