# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0009_auto_20171029_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
