# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0010_post_picture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profics',
            field=models.IntegerField(default=1),
        ),
    ]
