# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniconnect_app', '0011_auto_20171030_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profics',
            field=models.IntegerField(default=0),
        ),
    ]
